{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5fa81731-79c3-4f31-8433-6fd0a6f9ac33",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-03 18:49:15.156 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.090 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\mahes\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-12-03 18:49:16.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.096 Session state does not function when running a script without `streamlit run`\n",
      "2025-12-03 18:49:16.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.105 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.116 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.118 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.120 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.124 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-03 18:49:16.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import pickle\n",
    "\n",
    "# Load trained pipeline\n",
    "with open('cricket_pipeline_bits.pkl', 'rb') as f:\n",
    "    pipeline = pickle.load(f)\n",
    "\n",
    "# Teams and cities\n",
    "teams = [\n",
    "    'Australia', 'India', 'Bangladesh', 'New Zealand', 'South Africa', \n",
    "    'England', 'West Indies', 'Afghanistan', 'Pakistan', 'Sri Lanka'\n",
    "]\n",
    "\n",
    "cities = [\n",
    "    'Colombo', 'Kandy', 'Dambulla', 'Hambantota',  # Sri Lanka\n",
    "    'Napier', 'Mount Maunganui', 'Auckland', 'Wellington', 'Hamilton', 'Christchurch', 'Dunedin', 'Nelson', 'Queenstown',  # NZ\n",
    "    'Dhaka', 'Chattogram', 'Sylhet', 'Mirpur',  # Bangladesh\n",
    "    'Southampton', 'Taunton', 'Cardiff', 'Chester-le-Street', 'Birmingham', 'Manchester', 'Nottingham', 'Leeds', 'Bristol', 'London',  # England\n",
    "    'Bloemfontein', 'Potchefstroom', 'East London', 'Durban', 'Port Elizabeth', 'Gqeberha', 'Centurion', 'Cape Town', 'Paarl',  # South Africa\n",
    "    'Kanpur', 'Nagpur', 'Bangalore', 'Bengaluru', 'Ranchi', 'Guwahati', 'Delhi', 'Rajkot', 'Thiruvananthapuram', 'Cuttack', 'Indore',\n",
    "    'Mumbai', 'Kolkata', 'Lucknow', 'Chennai', 'Visakhapatnam', 'Hyderabad', 'Chandigarh', 'Pune', 'Jaipur', 'Dharamsala',  # India\n",
    "    'Lahore', 'Karachi', 'Rawalpindi',  # Pakistan\n",
    "    'Hobart', 'Adelaide', 'Melbourne', 'Sydney', 'Canberra', 'Perth', 'Darwin', 'Cairns',  # Australia\n",
    "    'Barbados', 'Trinidad', 'Jamaica', 'St Kitts', 'Gros Islet', 'Basseterre', 'Coolidge', 'Bridgetown', \"St George's\",\n",
    "    'Tarouba', 'Kingstown', 'St Lucia', 'Antigua', 'St Vincent', 'Providence', 'Guyana'  # West Indies\n",
    "]\n",
    "\n",
    "st.title(\"Cricket Runs Prediction\")\n",
    "\n",
    "# Dropdowns for teams and cities\n",
    "batting_team = st.selectbox(\"Batting Team\", teams)\n",
    "bowling_team = st.selectbox(\"Bowling Team\", teams)\n",
    "city = st.selectbox(\"City\", cities)\n",
    "\n",
    "# Numeric inputs\n",
    "current_score = st.number_input(\"Current Score\", min_value=0, max_value=500, value=100)\n",
    "balls_bowled = st.number_input(\"Balls Bowled\", min_value=0, max_value=300, value=60)\n",
    "wickets_left = st.number_input(\"Wickets Left\", min_value=0, max_value=10, value=5)\n",
    "runs_last_3_overs = st.number_input(\"Runs in Last 3 Overs\", min_value=0, max_value=100, value=20)\n",
    "crr = st.number_input(\"Current Run Rate\", min_value=0.0, max_value=20.0, value=6.0)\n",
    "\n",
    "# Predict button\n",
    "if st.button(\"Predict Runs\"):\n",
    "    X_new = pd.DataFrame([{\n",
    "        'batting_team': batting_team,\n",
    "        'bowling_team': bowling_team,\n",
    "        'city': city,\n",
    "        'current_score': current_score,\n",
    "        'balls_bowled': balls_bowled,\n",
    "        'wickets_left': wickets_left,\n",
    "        'runs_last_3_overs': runs_last_3_overs,\n",
    "        'crr': crr\n",
    "    }])\n",
    "    \n",
    "    predicted_runs = pipeline.predict(X_new)[0]\n",
    "    st.success(f\"Predicted Total Runs: {predicted_runs:.2f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac78cbe3-a1a5-469c-89ac-a4eed32ff189",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
